apiVersion: v1
kind: ServiceAccount
metadata:
  name: chain-reaction-agent
  namespace: chain-reaction
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chain-reaction-controller
  namespace: chain-reaction-controller
automountServiceAccountToken: false
